### ISSUE TITLE
activator not on PATH env

### ISSUE THREAD

**Issue by joantune** [cmoro-deusto/docker-play#4]
Hi!

I would do a PR but kinda constricted on time.

So, this line:

`RUN echo "export PATH=$PATH:/opt/activator" >> /home/play/.bashrc`
should be like this:
`RUN echo "export PATH=$PATH:/opt/activator/bin" >> /home/play/.bashrc`

Cheers and thanks for the awesome container.

**Comment by frite** [comment]
Created a PR https://github.com/cmoro-deusto/docker-play/pull/5

**Comment by joantune** [comment]
@cmoro-deusto: I confirm that downloading activator 1.3.9 the executables are now under /bin and that this PR makes sense.

If one wants to maintain compatibility with older versions, adding both PATHs can be the way to go. If not, please accept the PR

**Comment by cmoro-deusto** [comment]
Merged. Thanks a lot!!
