### ISSUE TITLE
Why not use the official java or openjdk base docker images?

### ISSUE THREAD

**Issue by chances** [cmoro-deusto/docker-play#7]
Is there some edge case that prevents the Dockerfile basing `FROM` the officially supported [java](https://hub.docker.com/_/java/) or [openjdk](https://hub.docker.com/_/openjdk/) base docker files?

**Comment by cmoro-deusto** [comment]
None actually. I just wanted to control what exactly was installed on the base image and use Oracle JDK, as openjdk is slower. The official java repo is deprecated.
